/*
 * beanTester.java
 *
 * Created on July 29, 2002, 11:59 AM
 */

package driver.ted.beans;

/**
 *
 * @author  tdriver
 */
public class beanTester extends javax.swing.JFrame {
    
    
    /** Creates new form beanTester */
    public beanTester() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        dateInputBean1 = new driver.ted.beans.TimeDate.DateInputBean();
        timeInputBean1 = new driver.ted.beans.TimeDate.TimeInputBean();
        julianDateInputBean1 = new driver.ted.beans.TimeDate.JulianDateInputBean();
        dateTimeSpinnerBean1 = new driver.ted.beans.TimeDate.dateTimeSpinnerBean();
        jTextField1 = new javax.swing.JTextField();
        locationInputBean1 = new driver.ted.beans.Location.LocationInputBean();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Bean Testing App");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        getContentPane().add(dateInputBean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        getContentPane().add(timeInputBean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(julianDateInputBean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 125, -1, 50));

        dateTimeSpinnerBean1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateTimeSpinnerBean1PropertyChange(evt);
            }
        });

        getContentPane().add(dateTimeSpinnerBean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 25, 230, 50));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 84, 130, -1));

        getContentPane().add(locationInputBean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 91, 290, 200));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-491)/2, (screenSize.height-347)/2, 491, 347);
    }//GEN-END:initComponents

    private void dateTimeSpinnerBean1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateTimeSpinnerBean1PropertyChange
       jTextField1.setText(String.valueOf(dateTimeSpinnerBean1.getDateTime()));
    }//GEN-LAST:event_dateTimeSpinnerBean1PropertyChange
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new beanTester().setVisible(true);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private driver.ted.beans.TimeDate.DateInputBean dateInputBean1;
    private driver.ted.beans.TimeDate.dateTimeSpinnerBean dateTimeSpinnerBean1;
    private javax.swing.JTextField jTextField1;
    private driver.ted.beans.TimeDate.JulianDateInputBean julianDateInputBean1;
    private driver.ted.beans.Location.LocationInputBean locationInputBean1;
    private driver.ted.beans.TimeDate.TimeInputBean timeInputBean1;
    // End of variables declaration//GEN-END:variables
    
}
