/*
 * HelpFrame.java
 *
 * Created on May 20, 2004, 12:49 PM
 */

package driver.ted.toolbox;
import javax.swing.text.*;
import javax.swing.*;
import javax.swing.event.*;
import java.io.*;
import java.net.URL;
/**
 *
 * @author  tdriver
 */
public class HelpFrame extends javax.swing.JInternalFrame {
    boolean shouldDisplay = true;
    /** Creates new form HelpFrame */
    public HelpFrame() {
        initComponents();
        openAndLoadFile();
        jEditorPane1.addHyperlinkListener(new HyperlinkListener (){
            public void hyperlinkUpdate(HyperlinkEvent e) {
  	          if (e.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
  		      JEditorPane pane = (JEditorPane) e.getSource();
  		      try {
  			   pane.setPage(e.getURL());
  		      } catch (Throwable t) {
  			   t.printStackTrace();
  		      }
  		   }
  	          }
            });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Help - Ted's Toolbox V2.0");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/driver/ted/toolbox/images/Help16.gif")));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jScrollPane1.setBorder(null);
        jEditorPane1.setEditable(false);
        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-727)/2, (screenSize.height-576)/2, 727, 576);
    }//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
       driver.ted.toolbox.ToolBoxApp.decrementFrameCount();
    }//GEN-LAST:event_formInternalFrameClosed
    
    public void openAndLoadFile(){
      // create the URL for the help file
    String s = null;
    try {
        s = "file:"
            + System.getProperty("user.dir")
            + System.getProperty("file.separator")
            + "ttbHelp\\ttbHelp.htm";
        URL helpURL = new URL(s);
        // set the page for the editor pane
         try {
              jEditorPane1.setPage(helpURL);
             } catch (IOException e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                          "Attempted to read a bad URL: " + helpURL,
                          "IO Exception",
                          javax.swing.JOptionPane.ERROR_MESSAGE);
                shouldDisplay = false;
             }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Couldn't create help URL: " + s,
                "Exception",
                javax.swing.JOptionPane.ERROR_MESSAGE);    
                shouldDisplay = false;
        }
    }
    
    public boolean shouldDisplayHelp() {
        return shouldDisplay;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
