/*
 * LunarToolFrame.java
 *
 * Created on September 10, 2002, 2:18 PM
 */

package driver.ted.toolbox;

import driver.ted.utilities.T_Converter;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author  tdriver
 */
public class NumberConversionFrame extends javax.swing.JInternalFrame {
    
    int inputType;
    int padType;
    String valueToConvert;
    boolean isApplet;
    
    /** Creates new form LunarRiseSetFrame */
      public NumberConversionFrame(boolean applet) {
          isApplet = applet;
        initComponents();
        inputType = T_Converter.INTEGER;
        padType = 0; // no padding
        valueToConvert = "";
    }
    
    
   
  private void calcConversions(){
    // set JtextFields 
    // to binary, octal, integer. and hex
    binaryOutput.setText(T_Converter.getBinary(valueToConvert,inputType,padType));
    octalOutput.setText(T_Converter.getOctal(valueToConvert,inputType));
    integerOutput.setText(T_Converter.getInt(valueToConvert,inputType));
    hexOutput.setText(T_Converter.getHex(valueToConvert,inputType).toUpperCase());
    binaryLength.setText(Integer.toString(T_Converter.getBinary(valueToConvert,inputType,padType).length()));
  }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        BinaryRadio = new javax.swing.JRadioButton();
        OctalRadio = new javax.swing.JRadioButton();
        HexRadio = new javax.swing.JRadioButton();
        IntegerRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        binaryOutput = new javax.swing.JTextField();
        binaryLength = new javax.swing.JTextField();
        octalOutput = new javax.swing.JTextField();
        integerOutput = new javax.swing.JTextField();
        hexOutput = new javax.swing.JTextField();
        noPadRadio = new javax.swing.JRadioButton();
        padForOctal = new javax.swing.JRadioButton();
        padForHex = new javax.swing.JRadioButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(135, 77, 48)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Number Conversions");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/driver/ted/toolbox/images/utilitiestool.gif")));
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(515, 341));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        buttonGroup1.add(BinaryRadio);
        BinaryRadio.setText("Binary");
        BinaryRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinaryRadioActionPerformed(evt);
            }
        });

        getContentPane().add(BinaryRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        buttonGroup1.add(OctalRadio);
        OctalRadio.setText("Octal");
        OctalRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctalRadioActionPerformed(evt);
            }
        });

        getContentPane().add(OctalRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        buttonGroup1.add(HexRadio);
        HexRadio.setText("Hex");
        HexRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexRadioActionPerformed(evt);
            }
        });

        getContentPane().add(HexRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        buttonGroup1.add(IntegerRadio);
        IntegerRadio.setSelected(true);
        IntegerRadio.setText("Integer");
        IntegerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntegerRadioActionPerformed(evt);
            }
        });

        getContentPane().add(IntegerRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel1.setText("Select Input Type");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTextField1.setText("1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });

        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 330, -1));

        jLabel2.setText("Enter Input ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));
        jLabel2.getAccessibleContext().setAccessibleName("Enter Input");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Binary");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, 50, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Octal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, 50, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Integer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, 50, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Hex");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, 50, -1));

        binaryOutput.setEditable(false);
        binaryOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(binaryOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 149, 430, -1));

        binaryLength.setEditable(false);
        binaryLength.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        binaryLength.setBorder(null);
        getContentPane().add(binaryLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 129, 40, -1));

        octalOutput.setEditable(false);
        octalOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(octalOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 179, 430, -1));

        integerOutput.setEditable(false);
        integerOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(integerOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 209, 430, -1));

        hexOutput.setEditable(false);
        hexOutput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(hexOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 239, 430, -1));

        buttonGroup2.add(noPadRadio);
        noPadRadio.setSelected(true);
        noPadRadio.setText("No Padding");
        noPadRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPadRadioActionPerformed(evt);
            }
        });

        getContentPane().add(noPadRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 119, -1, -1));

        buttonGroup2.add(padForOctal);
        padForOctal.setText("Pad For Octal");
        padForOctal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padForOctalActionPerformed(evt);
            }
        });

        getContentPane().add(padForOctal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 119, -1, -1));

        buttonGroup2.add(padForHex);
        padForHex.setText("Pad For Hex");
        padForHex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                padForHexActionPerformed(evt);
            }
        });

        getContentPane().add(padForHex, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 119, 100, -1));

        pack();
    }//GEN-END:initComponents

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        jTextField1.postActionEvent();
    }//GEN-LAST:event_jTextField1FocusLost

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        if(!isApplet){
            driver.ted.toolbox.ToolBoxApp.decrementFrameCount();
        }else{
            driver.ted.toolbox.ToolBoxJPanel.decrementFrameCount();
        }
    }//GEN-LAST:event_formInternalFrameClosed

    private void padForHexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padForHexActionPerformed
        padType = 4;
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_padForHexActionPerformed

    private void padForOctalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_padForOctalActionPerformed
        padType = 3;
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_padForOctalActionPerformed

    private void noPadRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPadRadioActionPerformed
        padType = 0;
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_noPadRadioActionPerformed

    private void HexRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexRadioActionPerformed
        inputType = T_Converter.HEX;
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_HexRadioActionPerformed

    private void IntegerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntegerRadioActionPerformed
        inputType = T_Converter.INTEGER;
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_IntegerRadioActionPerformed

    private void OctalRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctalRadioActionPerformed
        inputType = T_Converter.OCTAL;
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_OctalRadioActionPerformed

    private void BinaryRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinaryRadioActionPerformed
        inputType = T_Converter.BINARY;
        jTextField1ActionPerformed(evt);
    }//GEN-LAST:event_BinaryRadioActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
     // Enter pressed on the convert field.
    // validate input based on input type
    try{
      jTextField1.setText(jTextField1.getText().toUpperCase());
      Long.parseLong(jTextField1.getText(),inputType);
    }catch(NumberFormatException nfe){
      javax.swing.JOptionPane.showMessageDialog(this,
          "Number must integer of base " + inputType,
          "Error in Number Conversion Entry",
          javax.swing.JOptionPane.ERROR_MESSAGE);
      jTextField1.setText("0");
      jTextField1.requestFocusInWindow();
          return;
    }
    // passed validation
    valueToConvert = jTextField1.getText();
    calcConversions();
    }//GEN-LAST:event_jTextField1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BinaryRadio;
    private javax.swing.JRadioButton HexRadio;
    private javax.swing.JRadioButton IntegerRadio;
    private javax.swing.JRadioButton OctalRadio;
    private javax.swing.JTextField binaryLength;
    private javax.swing.JTextField binaryOutput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField hexOutput;
    private javax.swing.JTextField integerOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton noPadRadio;
    private javax.swing.JTextField octalOutput;
    private javax.swing.JRadioButton padForHex;
    private javax.swing.JRadioButton padForOctal;
    // End of variables declaration//GEN-END:variables
    
}
