/*
 * SolarRiseSetFrame.java
 *
 * Created on September 4, 2002, 8:36 AM
 */
package driver.ted.toolbox;
import driver.ted.astro.T_RiseSet;
import driver.ted.astro.T_SolarCoords;
import driver.ted.utilities.T_JulianDate;
import driver.ted.utilities.T_Utilities;
import driver.ted.utilities.T_Coordinates;
import java.util.prefs.Preferences;
import java.awt.event.*;

/**
 *
 * @author  tdriver
 */
public class SolarRiseSetFrame extends javax.swing.JInternalFrame {
    
    T_RiseSet RS;
    T_JulianDate jd = new T_JulianDate(); // jd is the local computer time
    T_SolarCoords SC = new T_SolarCoords(jd);
    Preferences prefs;
    final String latitudePref = "Latitude";
    final String longitudePref = "Longitude";
    final String timeOffsetPref = "TimeOffset";
    double activeLongitude;
    double activeLatitude;
    double activeTimeOffset;
    boolean isApplet;
    
    javax.swing.Timer timer1 = new javax.swing.Timer(1000,new ActionListener(){
      public void actionPerformed(ActionEvent evt) {
          jd.advance(0,0,0,0,0,1);
          updateActive();
        }
      }); 
    
    /** Creates new form SolarRiseSetFrame */
    public SolarRiseSetFrame(boolean applet) {
        isApplet = applet;
        initComponents();
        if(!isApplet){
            prefs = Preferences.userNodeForPackage(this.getClass());
            checkForStoredPreferences();
        }
        updateActive();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        activeDateField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        activeLatField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        activeLonField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        activeTOField = new javax.swing.JTextField();
        activeTimeField = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        changeActiveButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        RiseAzField = new javax.swing.JTextField();
        MaxElevationField = new javax.swing.JTextField();
        SetAzField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sunriseField = new javax.swing.JTextField();
        transitField = new javax.swing.JTextField();
        sunsetField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        amountOfDaylightField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        raField = new javax.swing.JTextField();
        declinationField = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        azField = new javax.swing.JTextField();
        elevationField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        julianDateInputBean1 = new driver.ted.beans.TimeDate.JulianDateInputBean();
        dateTimeSpinnerBean1 = new driver.ted.beans.TimeDate.dateTimeSpinnerBean();
        jLabel10 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 51)));
        setClosable(true);
        setIconifiable(true);
        setTitle("Daily Solar Tool");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/driver/ted/toolbox/images/solartool.gif")));
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(578, 478));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(new javax.swing.border.TitledBorder("Active Parameters"));
        jLabel6.setText("Time:");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        activeDateField.setEditable(false);
        activeDateField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        activeDateField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel5.add(activeDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 120, -1));

        jLabel7.setText("Latitude:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        activeLatField.setEditable(false);
        activeLatField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        activeLatField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel5.add(activeLatField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 120, -1));

        jLabel8.setText("Longitude:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        activeLonField.setEditable(false);
        activeLonField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        activeLonField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel5.add(activeLonField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, -1));

        jLabel9.setText("Time Offset:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        activeTOField.setEditable(false);
        activeTOField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        activeTOField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel5.add(activeTOField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 120, -1));

        activeTimeField.setEditable(false);
        activeTimeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(activeTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 120, -1));

        jLabel61.setText("Date:");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        changeActiveButton.setText("Change...");
        changeActiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActiveButtonActionPerformed(evt);
            }
        });

        jPanel5.add(changeActiveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, 180));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.EtchedBorder());
        jPanel31.setLayout(new java.awt.GridLayout(2, 3, 4, 0));

        jLabel11.setFont(new java.awt.Font("Dialog", 2, 12));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Rise Azimuth");
        jPanel31.add(jLabel11);

        jLabel31.setFont(new java.awt.Font("Dialog", 2, 12));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Max Elevation");
        jPanel31.add(jLabel31);

        jLabel41.setFont(new java.awt.Font("Dialog", 2, 12));
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Set Azimuth");
        jPanel31.add(jLabel41);

        RiseAzField.setEditable(false);
        RiseAzField.setFont(new java.awt.Font("Dialog", 1, 12));
        RiseAzField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RiseAzField.setBorder(null);
        RiseAzField.setRequestFocusEnabled(false);
        RiseAzField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel31.add(RiseAzField);

        MaxElevationField.setEditable(false);
        MaxElevationField.setFont(new java.awt.Font("Dialog", 1, 12));
        MaxElevationField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MaxElevationField.setBorder(null);
        MaxElevationField.setRequestFocusEnabled(false);
        MaxElevationField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel31.add(MaxElevationField);

        SetAzField.setEditable(false);
        SetAzField.setFont(new java.awt.Font("Dialog", 1, 12));
        SetAzField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SetAzField.setBorder(null);
        SetAzField.setRequestFocusEnabled(false);
        SetAzField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel31.add(SetAzField);

        jPanel2.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 40));

        jPanel3.setLayout(new java.awt.GridLayout(2, 3, 4, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sunrise");
        jPanel3.add(jLabel1);

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 12));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Transit");
        jPanel3.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 12));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sunset");
        jPanel3.add(jLabel4);

        sunriseField.setEditable(false);
        sunriseField.setFont(new java.awt.Font("Dialog", 1, 12));
        sunriseField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sunriseField.setBorder(null);
        sunriseField.setRequestFocusEnabled(false);
        sunriseField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel3.add(sunriseField);

        transitField.setEditable(false);
        transitField.setFont(new java.awt.Font("Dialog", 1, 12));
        transitField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        transitField.setBorder(null);
        transitField.setRequestFocusEnabled(false);
        transitField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel3.add(transitField);

        sunsetField.setEditable(false);
        sunsetField.setFont(new java.awt.Font("Dialog", 1, 12));
        sunsetField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sunsetField.setBorder(null);
        sunsetField.setRequestFocusEnabled(false);
        sunsetField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel3.add(sunsetField);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 40));

        jPanel4.setLayout(new java.awt.GridLayout(2, 3, 4, 3));

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 12));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Amount of Daylight");
        jPanel4.add(jLabel5);

        amountOfDaylightField.setEditable(false);
        amountOfDaylightField.setFont(new java.awt.Font("Dialog", 1, 12));
        amountOfDaylightField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        amountOfDaylightField.setBorder(null);
        amountOfDaylightField.setRequestFocusEnabled(false);
        amountOfDaylightField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel4.add(amountOfDaylightField);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 110, -1));

        jButton1.setText("Calculate");
        jButton1.setFocusCycleRoot(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 150, 100, -1));

        jTabbedPane1.addTab("Sun Rise / Set", jPanel2);

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        raField.setEditable(false);
        raField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        raField.setBorder(new javax.swing.border.TitledBorder("Right Ascension (h:m:s)"));
        raField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel21.add(raField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 40));

        declinationField.setEditable(false);
        declinationField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        declinationField.setBorder(new javax.swing.border.TitledBorder("Declination (d m s)"));
        declinationField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel21.add(declinationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 40));

        jToggleButton1.setText("Continuously Update");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jPanel21.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        azField.setEditable(false);
        azField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        azField.setBorder(new javax.swing.border.TitledBorder("Azimuth (degrees)"));
        azField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel21.add(azField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 150, 40));

        elevationField.setEditable(false);
        elevationField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        elevationField.setBorder(new javax.swing.border.TitledBorder("Elevation (degrees)"));
        elevationField.setSelectionColor(new java.awt.Color(255, 255, 51));
        jPanel21.add(elevationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, 40));

        jTabbedPane1.addTab("Coordinates", jPanel21);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 320, 210));

        jButton2.setText("Get Current Time");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 167, 140, 30));

        julianDateInputBean1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                julianDateInputBean1PropertyChange(evt);
            }
        });

        getContentPane().add(julianDateInputBean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 106, -1, -1));

        dateTimeSpinnerBean1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateTimeSpinnerBean1PropertyChange(evt);
            }
        });

        getContentPane().add(dateTimeSpinnerBean1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 47, 230, 50));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/driver/ted/toolbox/images/greenflash.jpg")));
        jLabel10.setFocusable(false);
        jLabel10.setMaximumSize(new java.awt.Dimension(600, 470));
        jLabel10.setMinimumSize(new java.awt.Dimension(600, 470));
        jLabel10.setPreferredSize(new java.awt.Dimension(600, 470));
        jLabel10.setRequestFocusEnabled(false);
        jLabel10.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -6, 580, 480));

        pack();
    }//GEN-END:initComponents

    private void dateTimeSpinnerBean1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateTimeSpinnerBean1PropertyChange
     jd = new T_JulianDate(dateTimeSpinnerBean1.getDateTime());
     updateActive();
    }//GEN-LAST:event_dateTimeSpinnerBean1PropertyChange

    private void changeActiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActiveButtonActionPerformed
        preferencesDialog pd = new preferencesDialog(null, true);
        pd.setLatitude(activeLatitude);
        pd.setLongitude(activeLongitude);
        pd.setTimeOffset(activeTimeOffset);        
        pd.setTitle("Solar Active Parameters");        
        pd.setVisible(true);
        if(pd.isUpdated()){
            activeLatitude = pd.getLatitude();
            activeLongitude = pd.getLongitude();
            activeTimeOffset = pd.getTimeOffset();
            updateActive();
        }
    }//GEN-LAST:event_changeActiveButtonActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        if(!isApplet){
            driver.ted.toolbox.ToolBoxApp.decrementFrameCount();
        }else{
            driver.ted.toolbox.ToolBoxJPanel.decrementFrameCount();
        }
    }//GEN-LAST:event_formInternalFrameClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jd = new T_JulianDate();
        updateActive();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if(jToggleButton1.isSelected()){
            timer1.start();
            jToggleButton1.setText("     Stop Updating    ");
        }else{
            timer1.stop();
            jToggleButton1.setText("Continuously Update");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void julianDateInputBean1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_julianDateInputBean1PropertyChange
        jd = new T_JulianDate(julianDateInputBean1.getJD());
        updateActive();
    }//GEN-LAST:event_julianDateInputBean1PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.text.DecimalFormat fm = new java.text.DecimalFormat("0.000");
        RS = new T_RiseSet(jd,activeLatitude,activeLongitude,(float)activeTimeOffset,T_RiseSet.SUN);
        sunriseField.setText(RS.getRiseTime());
        transitField.setText(RS.getTransitTime());
        sunsetField.setText(RS.getSetTime());
        RiseAzField.setText(fm.format(RS.getRiseAzimuth()));
        MaxElevationField.setText(fm.format(RS.getTransitElevation()));
        SetAzField.setText(fm.format(RS.getSetAzimuth()));
        amountOfDaylightField.setText(RS.getAmountOfDaylight());
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
   private void updateActive(){
        activeDateField.setText(jd.getDate().toMediumString());
        activeTimeField.setText(jd.getTime().toString());
        activeLatField.setText(new java.text.DecimalFormat("00.000").format(activeLatitude));
        activeLonField.setText(new java.text.DecimalFormat("000.000").format(activeLongitude));
        activeTOField.setText(new java.text.DecimalFormat("0.0").format(activeTimeOffset));
        T_JulianDate gmtjd = new T_JulianDate(jd.getJulianDate() - (activeTimeOffset/24.0));
        SC.setDateTime(gmtjd);
        double ra = SC.getAlpha_low();
        double dec = SC.getDelta_low();
        raField.setText(T_Utilities.decimalToRAHMS(ra,3)); // new java.text.DecimalFormat("0.000000").format(SC.getAlpha_low()));
        declinationField.setText(T_Utilities.decimalToDMSDIRV(dec,3)); //new java.text.DecimalFormat("0.000000").format(SC.getDelta_low())); //
        double[] azEl = new T_Coordinates().EquatorialToLocalHorizontal(ra,dec, activeLatitude,activeLongitude, gmtjd);
        
        azField.setText(new java.text.DecimalFormat("00.00").format(azEl[0]));
        elevationField.setText(new java.text.DecimalFormat("00.00").format(azEl[1]));
    }
    
    private void checkForStoredPreferences(){
       if(contains(prefs,latitudePref)){
           activeLatitude = prefs.getDouble(latitudePref,0.0);
       }else{
           activeLatitude = 0.0;
       }

       if(contains(prefs,longitudePref)){
           activeLongitude = prefs.getDouble(longitudePref,0.0);
       }else{
           activeLongitude = 0.0;
       }

       if(contains(prefs,timeOffsetPref)){
           activeTimeOffset = prefs.getDouble(timeOffsetPref,0);    
       }else{
           activeTimeOffset = 0.0;
       }
    }
    
    private static boolean contains(Preferences node, String key){
        return node.get(key,null) != null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MaxElevationField;
    private javax.swing.JTextField RiseAzField;
    private javax.swing.JTextField SetAzField;
    private javax.swing.JTextField activeDateField;
    private javax.swing.JTextField activeLatField;
    private javax.swing.JTextField activeLonField;
    private javax.swing.JTextField activeTOField;
    private javax.swing.JTextField activeTimeField;
    private javax.swing.JTextField amountOfDaylightField;
    private javax.swing.JTextField azField;
    private javax.swing.JButton changeActiveButton;
    private driver.ted.beans.TimeDate.dateTimeSpinnerBean dateTimeSpinnerBean1;
    private javax.swing.JTextField declinationField;
    private javax.swing.JTextField elevationField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private driver.ted.beans.TimeDate.JulianDateInputBean julianDateInputBean1;
    private javax.swing.JTextField raField;
    private javax.swing.JTextField sunriseField;
    private javax.swing.JTextField sunsetField;
    private javax.swing.JTextField transitField;
    // End of variables declaration//GEN-END:variables
    
}
