/*
 * splashPane2.java
 *
 * Created on October 2, 2002, 2:38 PM
 */

package driver.ted.toolbox;

import java.awt.*;
import java.awt.geom.*;

/**
 *
 * @author  tdriver
 */
public class splashPane2 extends javax.swing.JPanel {
    
    /** Creates new form splashPane2 */
    public splashPane2() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255)));
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(402, 123));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/driver/ted/toolbox/images/embarsa.gif")));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24));
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Ted's Toolbox");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel3.setText("Version 2.1");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel4.setText("Copyright (c) 2002-2005 Ted Driver");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

    }//GEN-END:initComponents
    
    public void paintComponent(Graphics g){
    Graphics2D g2d = (Graphics2D) g;
    super.paintComponent(g);
    g2d.setPaint(
          new GradientPaint(5,10, // x1 y1
                            // initial color
                            new Color(85,175,155),
                            5,130,  // x2, y2
                            new Color(106,74,74),//Color.black, // end color
                            false));   // cyclic
    g2d.fill(new Rectangle2D.Double(0,0,600,400));
   }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    
}
